image: node:6.4.0

stages:
  - build

build:
  stage: build
  script:
    - npm config set registry https://nexus.convergencelabs.tech/repository/npm/
    - npm config set //nexus.convergencelabs.tech/repository/npm/:_authToken=$NPM_TOKEN
    - npm config set //nexus.convergencelabs.tech/repository/convergence-npm/:_authToken=$C_NPM_TOKEN
    - npm install
    - npm run typings
    - npm run timestamp
    - npm run build
    - npm publish dist
