enum OperationType {
  COMPOUND = 0,
  ARRAY_INSERT = 1,
  ARRAY_MOVE = 2,
  ARRAY_REMOVE = 3,
  ARRAY_REPLACE = 4,
  ARRAY_SET = 5,
  BOOLEAN_SET = 6,
  NUMBER_ADD = 7,
  NUMBER_SET = 8,
  OBJECT_ADD_PROPERTY = 9,
  OBJECT_REMOVE_PROPERTY = 10,
  OBJECT_SET_PROPERTY = 11,
  OBJECT_SET = 12,
  STRING_INSERT = 13,
  STRING_REMOVE = 14,
  STRING_SET = 15
}

export default OperationType;
